# Generated by Django 3.1.3 on 2021-06-03 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20210603_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('M', 'Men'), ('W', 'Women'), ('S', 'Sport')], default='W', max_length=1),
        ),
    ]
