# Generated by Django 3.1.3 on 2021-06-03 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_auto_20210603_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Men', 'Men'), ('Woman', 'Woman'), ('Sport', 'Sport')], default='Woman', max_length=5),
        ),
    ]
