export const PRODUCT_FETCHING = "PRODUCT_FETCHING";
export const DETAIL_PRODUCT_FETCHING = "DETAIL_PRODUCT_FETCHING";
export const SET_LOADING = "SET_LOADING";
export const CLOSE_LOADING = "CLOSE_LOADING";
export const SEARCH = "SEARCH";